http:
  port: 49153
admin:
  port: 9877
  host: 192.168.10.169
apiEndpoints:
  irpdAPI:
    paths: ['/userLogin','/getUsers',/getUser/*,'/addUser','/updateUser','/deleteUser','/getJobs','/addJob',
    '/updateJob','/deleteJob','/search','/addCandidates','/getCandidates','/updateCandidates','/deleteCandidates/*',
    '/download/*','/addCandidatesResume','/updateCandidatesResume/*','/getPrevious_Exp/*','/getJobByStatus','/getCandidateByJob/*',
    '/getSkills','/addSkills','/updateSkills','/deleteSkills/*']
serviceEndpoints:   
  irpdServiceEndPoint:
    url: 'http://${USER_HOST}:${IRPD_PORT}/'
policies:
  - basic-auth
  - cors
  - key-auth
  - log
  - oauth2
  - proxy
  - jwt-auth
  - rate-limit
  - headers
  - expression
pipelines:
  default:
    apiEndpoints:
      - irpdAPI
    policies:
     # - jwt-auth:
      - proxy:
        - action:
            serviceEndpoint: irpdServiceEndPoint
            changeOrigin: true
  # devices:
  #   apiEndpoints:
  #     - devicesAPI
  #   policies:
  #    # - jwt-auth:
  #     - proxy:
  #       - action:
  #           serviceEndpoint: deviceServiceEndPoint
  #           changeOrigin: true
  
    
      
      
        
